# SPDX-FileCopyrightText: © 2024 Christopher Woods <Christopher.Woods@bristol.ac.uk>
# SPDX-FileCopyrightText: © 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "CHANGELOG.md"
SPDX-FileCopyrightText = "© 2024 Christopher Woods <Christopher.Woods@bristol.ac.uk>, Matt Williams <matt.williams@bristol.ac.uk>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
