# SPDX-FileCopyrightText: © 2024 Christopher Woods <Christopher.Woods@bristol.ac.uk>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "paddington"
version = "0.1.0"
description = "A library for implementing the OpenPortal communication protocol"
edition = "2021"
license = "MIT"
homepage = "https://github.com/chryswoods/openportal/"
repository = "https://github.com/chryswoods/openportal/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
futures-channel = "0.3.30"
futures-util = "0.3.30"
orion = "0.17.6"
secrecy = "0.8.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tokio = "1.38.1"
tokio-serde = "0.9.0"
tokio-tungstenite = "0.23.1"

[lints.rust]
unsafe_code = "forbid"
unused_crate_dependencies = "warn"

[lints.clippy]
dbg_macro = "deny"
unwrap_used = "deny"
expect_used = "deny"

[package.metadata.clippy]
allow-dbg-in-tests = true
