# SPDX-FileCopyrightText: © 2024 Christopher Woods <Christopher.Woods@bristol.ac.uk>
# SPDX-FileCopyrightText: © 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-portal
  labels:
    {{- include "op-portal.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: op-portal
  template:
    metadata:
      labels:
        {{- include "op-portal.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ pick (include (print $.Template.BasePath "/configmap.yaml") . | fromYaml) "data" | toString | sha1sum }}  # restart if config changed
    spec:
      containers:
        - name: op-portal
          image: "{{ print .Values.image.registry "/" }}{{ required "image_name must be set" .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          args: ["--config-file=/config/config.toml", "run"]
          env:
            - name: RUST_LOG
              value: {{ .Values.log_level | quote }}
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
          volumeMounts:
            - mountPath: {{ required "config_dir must be set" .Values.config_dir | quote }}
              name: "config-volume"
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - "ALL"
              add:
                - "NET_BIND_SERVICE"
      volumes:
          - name: "config-volume"
            secret:
              secretName: {{ .Values.secret_name | quote }}
